[versions]
dependencyUpdates = "0.50.0"
detekt = "1.23.4"
kotlin = "1.9.21"
toolchainsResolver = "0.7.0"

[plugins]
dependencyUpdates = { id = "com.github.ben-manes.versions", version.ref = "dependencyUpdates" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
toolchainsResolver = { id = "org.gradle.toolchains.foojay-resolver-convention", version.ref = "toolchainsResolver" }

[libraries]
detektFormatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }
